apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_name
  labels:
    app: app_name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app_name
  template:
    metadata:
      labels:
        app: app_name
    spec:
      containers:
      - name: app_name
        image: busayr/app_name:app_version
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app_name
spec:
  selector:
    app: app_name
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  name: app_name
spec:
  rules:
  - host: app_name.devops-tech.net
    http: 
      paths:
      - path: /
        backend:
          serviceName: app_name
          servicePort: 8080
  tls:
      - hosts:
          - app_name.devops-tech.net
        secretName: app_name-tls
